### ISSUE TITLE
Can the RPC continue to make smaller changes to the style guide

### ISSUE THREAD

**Issue by JayDaley** [intarchboard/program-rfced-future#58] opened 2021-05-06 00:32 UTC
Will the RPC be able to continue to make smaller updates to the online portion of the style guide and various lists as they do now?

**Comment by stpeter** [comment] 2021-08-02 21:02
Version -01 of the draft says that the following is in scope for the RPC:

>   o  Maintenance of a styleguide that defines editorial standards to
>      which RFCs must adhere (see [RFC7322] and related updates).

**Comment by elear** [comment] 2021-08-14 09:13
Issue #79 is a duplicate of this issue, and these two will be handled together, given that discussion is going on with the other issue.

**Closed** 2021-09-10 21:31 UTC
Labels: Propose to close
